/** Reasonably complete list of countries by ISO 3166-1 alpha-2 codes, grouped into arbitrary regions */
const globalRegions = {
	'northern africa': {
		DZ: 'Algeria',
		IC: 'The Canary Islands',
		EG: 'Egypt',
		LY: 'Libya',
		MA: 'Morocco',
		SS: 'South Sudan',
		TN: 'Tunisia',
		EH: 'Western Sahara'
	},
	'eastern africa': {
		BI: 'Burundi',
		KM: 'Comoros',
		DJ: 'Djibouti',
		ER: 'Eritrea',
		ET: 'Ethiopia',
		KE: 'Kenya',
		MG: 'Madagascar',
		MW: 'Malawi',
		MU: 'Mauritius',
		YT: 'Mayotte',
		MZ: 'Mozambique',
		RE: 'Réunion',
		RW: 'Rwanda',
		SC: 'Seychelles',
		SO: 'Somalia',
		TZ: 'Tanzania',
		UG: 'Uganda',
		ZM: 'Zambia',
		ZW: 'Zimbabwe'
	},
	'southern africa': {
		BW: 'Botswana',
		LS: 'Lesotho',
		NA: 'Namibia',
		ZA: 'South Africa',
		SZ: 'Eswatini'
	},
	'central africa': {
		AO: 'Angola',
		CM: 'Cameroon',
		CF: 'Central African Republic',
		TD: 'Chad',
		CG: 'Congo',
		CD: 'Congo, Democratic Republic of the',
		GQ: 'Equatorial Guinea',
		GA: 'Gabon',
		ST: 'Sao Tome and Principe'
	},
	'western africa': {
		BJ: 'Benin',
		BF: 'Burkina Faso',
		CV: 'Cabo Verde',
		CI: 'Côte d\'Ivoire',
		GM: 'Gambia',
		GH: 'Ghana',
		GN: 'Guinea',
		GW: 'Guinea-Bissau',
		LR: 'Liberia',
		ML: 'Mali',
		MR: 'Mauritania',
		NE: 'Niger',
		NG: 'Nigeria',
		SH: 'Saint Helena, Ascension and Tristan da Cunha',
		SN: 'Senegal',
		SL: 'Sierra Leone',
		TG: 'Togo'
	},
	'asia': {
		AF: 'Afghanistan',
		AM: 'Armenia',
		AZ: 'Azerbaijan',
		BD: 'Bangladesh',
		BT: 'Bhutan',
		BN: 'Brunei Darussalam',
		KH: 'Cambodia',
		CN: 'China',
		GE: 'Georgia',
		HK: 'Hong Kong',
		IN: 'India',
		ID: 'Indonesia',
		JP: 'Japan',
		KZ: 'Kazakhstan',
		KP: 'Korea (Democratic People\'s Republic of)',
		KR: 'Korea, Republic of',
		KG: 'Kyrgyzstan',
		LA: 'Lao People\'s Democratic Republic',
		MO: 'Macao',
		MY: 'Malaysia',
		MV: 'Maldives',
		MN: 'Mongolia',
		MM: 'Myanmar',
		NP: 'Nepal',
		PK: 'Pakistan',
		PH: 'Philippines',
		SG: 'Singapore',
		LK: 'Sri Lanka',
		TW: 'Taiwan',
		TJ: 'Tajikistan',
		TH: 'Thailand',
		TL: 'Timor-Leste',
		TM: 'Turkmenistan',
		UZ: 'Uzbekistan',
		VN: 'Viet Nam'
	},
	'europe': {
		AL: 'Albania',
		AD: 'Andorra',
		AT: 'Austria',
		BY: 'Belarus',
		BE: 'Belgium',
		BA: 'Bosnia and Herzegovina',
		BG: 'Bulgaria',
		HR: 'Croatia',
		CY: 'Cyprus',
		DK: 'Denmark',
		EE: 'Estonia',
		FO: 'Faroe Islands',
		FI: 'Finland',
		FR: 'France',
		DE: 'Germany',
		GI: 'Gibraltar',
		GR: 'Greece',
		GG: 'Guernsey',
		HU: 'Hungary',
		IS: 'Iceland',
		IE: 'Ireland',
		IT: 'Italy',
		JE: 'Jersey',
		XK: 'Kosovo',
		LV: 'Latvia',
		LI: 'Liechtenstein',
		LT: 'Lithuania',
		LU: 'Luxembourg',
		MK: 'North Macedonia',
		MT: 'Malta',
		MD: 'Moldova, Republic of',
		MC: 'Monaco',
		ME: 'Montenegro',
		NL: 'Netherlands',
		NO: 'Norway',
		PL: 'Poland',
		PT: 'Portugal',
		RO: 'Romania',
		RU: 'Russian Federation',
		SM: 'San Marino',
		RS: 'Serbia',
		SI: 'Slovenia',
		SK: 'Slovakia',
		ES: 'Spain',
		SJ: 'Svalbard and Jan Mayen',
		SE: 'Sweden',
		CH: 'Switzerland',
		CZ: 'Czechia',
		IM: 'Isle of Man',
		TR: 'Turkey',
		UA: 'Ukraine',
		GB: 'United Kingdom',
		VA: 'Vatican City'
	},
	'central america': {
		BZ: 'Belize',
		CR: 'Costa Rica',
		SV: 'El Salvador',
		GT: 'Guatemala',
		HN: 'Honduras',
		MX: 'Mexico',
		NI: 'Nicaragua',
		PA: 'Panama'
},
	'south america': {
		AR: 'Argentina',
		BO: 'Bolivia',
		BR: 'Brazil',
		CL: 'Chile',
		CO: 'Colombia',
		EC: 'Ecuador',
		FK: 'Falkland Islands',
		GF: 'French Guiana',
		GY: 'Guyana',
		PY: 'Paraguay',
		PE: 'Peru',
		SR: 'Suriname',
		UY: 'Uruguay',
		VE: 'Venezuela'
	},
	'middle east': {
		BH: 'Bahrain',
		IQ: 'Iraq',
		IR: 'Iran',
		IL: 'Israel',
		JO: 'Jordan',
		KW: 'Kuwait',
		LB: 'Lebanon',
		OM: 'Oman',
		PS: 'Palestine',
		QA: 'Qatar',
		SA: 'Saudi Arabia',
		SY: 'Syria',
		AE: 'The United Arab Emirates',
		YE: 'Yemen',
	},
	'oceania': {
		AU: 'Australia',
		FJ: 'Fiji',
		PF: 'French Polynesia',
		GU: 'Guam',
		KI: 'Kiribati',
		MH: 'Marshall Islands',
		FM: 'Micronesia (Federated States of)',
		NC: 'New Caledonia',
		NZ: 'New Zealand',
		PG: 'Papua New Guinea',
		WS: 'Samoa',
		AS: 'American Samoa',
		SB: 'Solomon Islands',
		VU: 'Vanuatu'
	},
	'north america': {
		US: 'The United States',
		CA: 'Canada',
		GL: 'Greenland',
		PM: 'Saint Pierre and Miquelon',
		BM: 'Bermuda'
	},
	'the caribbean': {
		AI: 'Anguilla',
		AG: 'Antigua and Barbuda',
		BS: 'Bahamas',
		BB: 'Barbados',
		KY: 'Cayman Islands',
		CU: 'Cuba',
		DM: 'Dominica',
		DO: 'Dominican Republic',
		GD: 'Grenada',
		GP: 'Guadeloupe',
		HT: 'Haiti',
		JM: 'Jamaica',
		MQ: 'Martinique',
		PR: 'Puerto Rico',
		BL: 'St Barthelemy',
		KN: 'St Kitts and Nevis',
		LC: 'St Lucia',
		SX: 'St Maarten',
		MF: 'St Martin',
		VC: 'St Vincent and the Grenadines',
		TT: 'Trinidad and Tobago',
		TC: 'Turks and Caicos Islands',
		VG: 'Virgin Islands, UK',
		VI: 'Virgin Islands, US',
	}
};

export {
	globalRegions,
}